# Generated by Django 5.0.6 on 2024-05-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
